export struct Solana {
    amount: string,
    amount_int: float,
    mint: string,
    name: string,
    symbol: string,
    image: image,
    price: float,
    balance: float,
}

export struct Token {
    amount: string,
    amount_int: float,
    amount_formatted: string,
    description: string,
    image: image,
    mint: string,
    name: string,
    owner: string,
    symbol: string,
    price: float,
    balance: float,
}